CREATE TABLE usuarios (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nombre VARCHAR(255) NOT NULL,
                          email VARCHAR(255) NOT NULL UNIQUE,
                          password VARCHAR(255) NOT NULL,
                          rol VARCHAR(255) NOT NULL,

                          CONSTRAINT chk_usuario_rol
                              CHECK (rol IN ('CLIENTE', 'OPERADOR', 'ADMIN'))
);

CREATE TABLE productos (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           nombre VARCHAR(255) NOT NULL,
                           descripcion VARCHAR(255) NOT NULL,
                           activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE compras (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         fecha DATE NOT NULL,
                         total NUMERIC(10,2) NOT NULL,
                         estado VARCHAR(255) NOT NULL,
                         usuario_id BIGINT NOT NULL,

                         CONSTRAINT fk_compra_usuario
                             FOREIGN KEY (usuario_id)
                                 REFERENCES usuarios(id),

                         CONSTRAINT chk_compra_estado
                             CHECK (estado IN ('ENTREGADA', 'EN_TRANSITO'))
);

CREATE TABLE detalle_compras (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 cantidad INTEGER NOT NULL,
                                 precio_unitario NUMERIC(10,2) NOT NULL,
                                 compra_id BIGINT NOT NULL,
                                 producto_id BIGINT NOT NULL,

                                 CONSTRAINT fk_detalle_compra
                                     FOREIGN KEY (compra_id)
                                         REFERENCES compras(id),

                                 CONSTRAINT fk_detalle_producto
                                     FOREIGN KEY (producto_id)
                                         REFERENCES productos(id),

                                 CONSTRAINT chk_detalle_compra_cantidad
                                     CHECK (cantidad > 0)
);

CREATE TABLE solicitudes_devolucion (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        fecha_solicitud TIMESTAMP NOT NULL,
                                        estado VARCHAR(255) NOT NULL,
                                        motivo VARCHAR(255) NOT NULL,
                                        comentario VARCHAR(500),
                                        observacion_operador VARCHAR(500),
                                        importe NUMERIC(10,2) NOT NULL,
                                        compra_id BIGINT NOT NULL,
                                        usuario_id BIGINT NOT NULL,

                                        CONSTRAINT fk_devolucion_compra
                                            FOREIGN KEY (compra_id)
                                                REFERENCES compras(id),

                                        CONSTRAINT fk_devolucion_usuario
                                            FOREIGN KEY (usuario_id)
                                                REFERENCES usuarios(id),

                                        CONSTRAINT chk_devolucion_estado
                                            CHECK (
                                                estado IN (
                                                           'SOLICITADA',
                                                           'EN_REVISION',
                                                           'APROBADA',
                                                           'RECHAZADA',
                                                           'COMPLETADA'
                                                    )
                                                ),

                                        CONSTRAINT chk_devolucion_motivo
                                            CHECK (
                                                motivo IN (
                                                           'PRODUCTO_DEFECTUOSO',
                                                           'PRODUCTO_INCORRECTO',
                                                           'PRODUCTO_DANADO',
                                                           'NO_CUMPLE_EXPECTATIVAS',
                                                           'OTRO'
                                                    )
                                                )
);

CREATE TABLE detalle_devoluciones (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      cantidad INTEGER NOT NULL,
                                      importe NUMERIC(10,2) NOT NULL,
                                      solicitud_id BIGINT NOT NULL,
                                      detalle_compra_id BIGINT NOT NULL,

                                      CONSTRAINT fk_detalle_devolucion_solicitud
                                          FOREIGN KEY (solicitud_id)
                                              REFERENCES solicitudes_devolucion(id),

                                      CONSTRAINT fk_detalle_devolucion_compra
                                          FOREIGN KEY (detalle_compra_id)
                                              REFERENCES detalle_compras(id),

                                      CONSTRAINT chk_detalle_devolucion_cantidad
                                          CHECK (cantidad > 0)
);